trigger:
  branches:
    include:
      - release 'main' # Synapse collaboration branch

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  displayName: 'Checkout triggering branch'
  clean: true
  fetchDepth: 0

- task: Synapse workspace deployment@2
  inputs:
    operation: 'validate'
    ArtifactsFolder: '$(System.DefaultWorkingDirectory)'
    azureSubscription: '26c1fddb-1b8b-4755-a146-a7f8bfe73f39'
    ResourceGroupName: 'yoferg'
    TargetWorkspaceName: 'adfdevyofe'
